# https://docs.docker.com/compose/compose-file/#/versioning
version: '3'

services:
  nginx:
    # https://hub.docker.com/_/nginx
    container_name: laravel-nginx
    build: ./docker/nginx
    depends_on:
      - php
    volumes:
      - ./:/var/www/vhost/:cached
    working_dir: /var/www/vhost/
    ports:
      - '80:80'
      - '443:443'
    networks:
      - docker_network

  php:
    # https://hub.docker.com/_/php
    container_name: laravel-php
    build: ./docker/php
    environment:
      PHP_MEMORY_LIMIT: '128M'
      COMPOSER_MEMORY_LIMIT: '-1'
    volumes:
      - ./:/var/www/vhost/:cached
    working_dir: /var/www/vhost/
    ports:
      - '9000:9000'
    networks:
      - docker_network

  node:
    # https://hub.docker.com/_/node
    container_name: laravel-node
    image: "node:15"
    user: "node"
    environment:
      NODE_ENV: 'development'
    volumes:
      - ./:/var/www/vhost/:cached
    working_dir: /var/www/vhost/
    networks:
      - docker_network
    command: "npm install"

  mysql:
    # https://hub.docker.com/r/mysql/mysql-server/
    container_name: laravel-mysql
    image: mysql/mysql-server:latest
    volumes:
      - laravel-mysql-data-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'local'
      MYSQL_ROOT_HOST: '%'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - docker_network
    ports:
      - 4406:3306

volumes:
  laravel-mysql-data-volume:

networks:
  docker_network:
    driver: bridge
